// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbsJDz5dLe7XhvjJfLLy984LwjIX8CDCA',
    appId: '1:251896773022:web:3127366d5ee8d28561fe8f',
    messagingSenderId: '251896773022',
    projectId: 'web-responsive-86326',
    authDomain: 'web-responsive-86326.firebaseapp.com',
    databaseURL:
        'https://web-responsive-86326-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'web-responsive-86326.appspot.com',
    measurementId: 'G-Z3KZ0JMG4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPgNqoFcIS0-JMzNS_GwJEi7N1ujck50',
    appId: '1:251896773022:android:55932149b4d167d661fe8f',
    messagingSenderId: '251896773022',
    projectId: 'web-responsive-86326',
    databaseURL:
        'https://web-responsive-86326-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'web-responsive-86326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDboKGXJ49IFViowiTr6NazuUDqRD41cw',
    appId: '1:251896773022:ios:b236c07cb8726e3361fe8f',
    messagingSenderId: '251896773022',
    projectId: 'web-responsive-86326',
    databaseURL:
        'https://web-responsive-86326-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'web-responsive-86326.appspot.com',
    iosBundleId: 'com.example.webResponsiveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDboKGXJ49IFViowiTr6NazuUDqRD41cw',
    appId: '1:251896773022:ios:b236c07cb8726e3361fe8f',
    messagingSenderId: '251896773022',
    projectId: 'web-responsive-86326',
    databaseURL:
        'https://web-responsive-86326-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'web-responsive-86326.appspot.com',
    iosBundleId: 'com.example.webResponsiveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbsJDz5dLe7XhvjJfLLy984LwjIX8CDCA',
    appId: '1:251896773022:web:df0957b1acb9de9861fe8f',
    messagingSenderId: '251896773022',
    projectId: 'web-responsive-86326',
    authDomain: 'web-responsive-86326.firebaseapp.com',
    databaseURL:
        'https://web-responsive-86326-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'web-responsive-86326.appspot.com',
    measurementId: 'G-7XSVX61Y7Z',
  );
}
